### ISSUE TITLE
Issue with Musicbee version 3.5.8367

### ISSUE THREAD

**Issue by krilok** [imak101/MusicBee-UserCosmetics#5]
Hi...

Just wanted to let you know that after updating to the latest MusicBee release (3.5.8367), upon launch MB completely freezes and won't respond to any interaction, so after some troubleshooting, it seems that the issue is caused by the UserCosmetics plugin. 

If the plugin is enabled, MB will freeze, and the only option is to force quit the app. However, if I downgrade to a previous version of MB, there are no issues and all seems to work well, and if I reinstall MB 3.5.8367 with UserCosmetics disabled, everything's fine, too, so perhaps the plugin is now incompatible with the latest MB changes and needs an upgrade.

Maybe when you get the chance you can look into it? Thank you.

**Comment by imak101** [comment]
I'll look into this as soon as possible. Thank you!

**Comment by krilok** [comment]
> I'll look into this as soon as possible. Thank you!

Thank you... ;)

**Comment by imak101** [comment]
Okay, it looks like the issue was being caused by a call to Invoke() on the main Control housing the PictureBox. I fixed it by making this call lazy, and not right at plugin initialization.  

I hope this fix works for you @krilok!

**Comment by krilok** [comment]
> Okay, it looks like the issue was being caused by a call to Invoke() on the main Control housing the PictureBox. I fixed it by making this call lazy, and not right at plugin initialization.
> 
> I hope this fix works for you @krilok!

All working well now... Thank you for the quick fix.
